/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Neural Inverse Corporation. All rights reserved.
 *  Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/**
 * # Built-in Rules — Platform Baseline
 *
 * Comprehensive baseline GRC rules that work out of the box across ALL industries
 * and languages — no company framework configuration required.
 *
 * ## Philosophy
 *
 * Neural Inverse is a platform designed for regulated and safety-critical software
 * development. Companies may not know which specific GRC rules to define, so the
 * platform ships with a comprehensive baseline covering:
 *
 * - Universal security (all languages): credentials, injection, XSS, crypto, logging
 * - Data integrity: SQL injection, NoSQL injection, path traversal
 * - Architecture: God files, circular dependency signals
 * - Fail-safe defaults: unhandled errors, missing null checks, exception swallowing
 * - C/C++ structural safety: MISRA C, AUTOSAR, ISO 26262, ISR safety (15 checks)
 * - Critical Infrastructure (ICS/SCADA): IEC 62443, NERC CIP, DNP3, Modbus, OPC-UA (10 checks)
 * - Telecom & 5G: 3GPP, GSMA, SIP, GTP, NAS, Diameter, SS7 (9 checks)
 * - Industrial IoT / OT: IEC 61508, ISA/IEC 62443, real-time safety (10 checks)
 *
 * Companies can extend these via `.inverse/frameworks/`, disable individual rules,
 * or override severities via `.inverse/grc-rules.json` frameworkOverrides.
 *
 * ## Available Check Types
 *
 * | Type               | Analyzer              | What It Does                                      |
 * |--------------------|-----------------------|---------------------------------------------------|
 * | `regex`            | Built-in engine       | Line-by-line pattern matching                     |
 * | `universal`        | UniversalAnalyzer     | Multi-language pattern (with per-lang variants)   |
 * | `file-level`       | Built-in engine       | File-level checks (max lines, missing headers)    |
 * | `ast`              | AstAnalyzer           | TypeScript AST structural analysis                |
 * | `dataflow`         | DataFlowAnalyzer      | Taint tracking: source \u2192 sink                     |
 * | `import-graph`     | ImportGraphAnalyzer   | Module boundary / layer violation detection       |
 * | `c-structural`     | CStructuralAnalyzer   | MISRA C / AUTOSAR / ISO 26262 / ISR safety        |
 * | `ics-security`     | ICSSecurityAnalyzer   | ICS/SCADA security (IEC 62443, NERC CIP)          |
 * | `telecom-security` | TelecomSecurityAnalyzer | 3GPP/GSMA/SIP/GTP/NAS/Diameter/SS7 security     |
 * | `iot-ot`           | IndustrialIotAnalyzer | Industrial IoT/OT real-time safety               |
 */

import { IFrameworkDefinition } from '../framework/frameworkSchema.js';
import { IGRCRule } from '../types/grcTypes.js';


// ─── Built-in Framework Definition ───────────────────────────────────────────

export const BUILTIN_FRAMEWORK: IFrameworkDefinition = {
	framework: {
		id: 'neural-inverse-builtin',
		name: 'Neural Inverse Platform',
		version: '3.0.0',
		description: 'Comprehensive out-of-the-box GRC baseline — covers all industries and languages. No configuration required.',
		authority: 'Neural Inverse',
	},

	rules: [],

	categories: {
		'security':       { label: 'Security',        icon: 'shield',        color: '#ff5252' },
		'compliance':     { label: 'Compliance',       icon: 'verified',      color: '#ffd740' },
		'data-integrity': { label: 'Data Integrity',   icon: 'database',      color: '#ab47bc' },
		'architecture':   { label: 'Architecture',     icon: 'layers',        color: '#42a5f5' },
		'fail-safe':      { label: 'Fail-Safe',        icon: 'error',         color: '#ff7043' },
		'policy':         { label: 'Policy',           icon: 'policy',        color: '#66bb6a' },
		'privacy':        { label: 'Privacy',          icon: 'lock',          color: '#7c4dff' },
		'performance':    { label: 'Performance',      icon: 'dashboard',     color: '#26c6da' },
		'reliability':    { label: 'Reliability',      icon: 'verified_user', color: '#9ccc65' },
		'ics-security':   { label: 'ICS/SCADA',        icon: 'factory',       color: '#ff6e40' },
		'telecom-security': { label: 'Telecom/5G',     icon: 'cell_tower',    color: '#40c4ff' },
		'ot-safety':      { label: 'OT/Industrial',    icon: 'precision_manufacturing', color: '#69f0ae' },
		'firmware':       { label: 'Firmware/Embedded',icon: 'memory',        color: '#ea80fc' },
		'automotive':     { label: 'Automotive',       icon: 'directions_car',color: '#ffff00' },
	},
};


// ─── Universal Security Rules (all languages) ────────────────────────────────

const SECURITY_RULES: IGRCRule[] = [
	{
		id: 'SEC-001',
		domain: 'security',
		severity: 'error',
		type: 'universal',
		pattern: '',
		check: {
			type: 'universal',
			pattern: '\\b(password|passwd|pwd|secret|api_key|apikey|access_key|private_key|client_secret|auth_token|signing_key|encryption_key)\\s*[=:]\\s*["\'][^"\']{4,}["\']',
			excludeContexts: [],
			languagePatterns: {
				python: '\\b(PASSWORD|PASSWD|SECRET|API_KEY|ACCESS_KEY|PRIVATE_KEY|TOKEN)\\s*=\\s*["\'][^"\']{4,}["\']',
				java: '(?:String|final\\s+String)\\s+(?:password|secret|apiKey|accessKey|privateKey|token)\\s*=\\s*"[^"]+"',
				c: '(?:char|const char)\\s*\\*?\\s*(?:password|secret|api_key|access_key|private_key)\\s*=\\s*"[^"]+"',
				cpp: '(?:std::string|const char)\\s*\\*?\\s*(?:password|secret|api_key|access_key|private_key)\\s*=\\s*"[^"]+"',
				go: '(?:password|secret|apiKey|accessKey|privateKey|token)\\s*(?::=|=)\\s*"[^"]+"',
				rust: 'let\\s+(?:mut\\s+)?(?:password|secret|api_key|access_key|private_key|token)\\s*[=:]\\s*"[^"]+"',
			},
		},
		message: 'Hardcoded credential or secret — use a secrets manager, environment variable, or encrypted vault',
		fix: 'Move to environment variable or secrets manager (e.g. AWS Secrets Manager, HashiCorp Vault)',
		enabled: true,
		builtin: true,
		references: ['CWE-798', 'OWASP A07:2021'],
		tags: ['credential', 'secret', 'hardcoded'],
	},
	{
		id: 'SEC-002',
		domain: 'security',
		severity: 'error',
		type: 'regex',
		pattern: '\\beval\\s*\\(',
		check: { type: 'regex', pattern: '\\beval\\s*\\(' },
		message: 'Dangerous eval() call — arbitrary code execution risk',
		fix: 'Replace eval() with a safe alternative (JSON.parse, Function constructors with validation, etc.)',
		enabled: true,
		builtin: true,
		references: ['CWE-95', 'OWASP A03:2021'],
		tags: ['injection', 'code-execution'],
	},
	{
		id: 'SEC-003',
		domain: 'security',
		severity: 'error',
		type: 'regex',
		pattern: 'innerHTML\\s*=|document\\.write\\s*\\(|outerHTML\\s*=',
		check: { type: 'regex', pattern: 'innerHTML\\s*=|document\\.write\\s*\\(|outerHTML\\s*=' },
		message: 'Direct DOM manipulation with innerHTML/document.write — XSS risk if user data is present',
		fix: 'Use textContent or a safe DOM manipulation library (DOMPurify, etc.)',
		enabled: true,
		builtin: true,
		references: ['CWE-79', 'OWASP A03:2021'],
		tags: ['xss', 'dom', 'injection'],
	},
	{
		id: 'SEC-004',
		domain: 'security',
		severity: 'error',
		type: 'regex',
		pattern: 'dangerouslySetInnerHTML\\s*=\\s*\\{',
		check: { type: 'regex', pattern: 'dangerouslySetInnerHTML\\s*=\\s*\\{' },
		message: 'React dangerouslySetInnerHTML detected — XSS risk if value contains user data',
		fix: 'Sanitize content with DOMPurify before passing to dangerouslySetInnerHTML',
		enabled: true,
		builtin: true,
		references: ['CWE-79', 'OWASP A03:2021'],
		tags: ['xss', 'react'],
	},
	{
		id: 'SEC-005',
		domain: 'security',
		severity: 'error',
		type: 'regex',
		pattern: 'child_process|exec\\s*\\(|spawn\\s*\\(|execSync\\s*\\(|spawnSync\\s*\\(',
		check: { type: 'regex', pattern: 'child_process|exec\\s*\\(|spawn\\s*\\(|execSync\\s*\\(|spawnSync\\s*\\(' },
		message: 'Shell command execution detected — command injection risk if arguments contain user input',
		fix: 'Use parameterized arguments, avoid shell: true, validate all inputs before shell execution',
		enabled: true,
		builtin: true,
		references: ['CWE-78', 'OWASP A03:2021'],
		tags: ['command-injection', 'shell'],
	},
	{
		id: 'SEC-006',
		domain: 'security',
		severity: 'warning',
		type: 'regex',
		pattern: '\\b(MD5|md5|SHA1|sha1)\\s*[\\(\\.]',
		check: { type: 'regex', pattern: '\\b(MD5|md5|SHA1|sha1)\\s*[\\(\\.]' },
		message: 'Weak cryptographic hash (MD5/SHA1) — these are broken and unsuitable for security',
		fix: 'Use SHA-256 or stronger (SHA-3, BLAKE2). For passwords use bcrypt/scrypt/argon2.',
		enabled: true,
		builtin: true,
		references: ['CWE-327', 'OWASP A02:2021'],
		tags: ['crypto', 'weak-hash'],
	},
	{
		id: 'SEC-007',
		domain: 'security',
		severity: 'error',
		type: 'regex',
		pattern: 'Math\\.random\\s*\\(\\)|random\\.random\\s*\\(\\)|rand\\s*\\(\\)|srand\\s*\\(',
		check: { type: 'regex', pattern: 'Math\\.random\\s*\\(\\)|random\\.random\\s*\\(\\)|rand\\s*\\(\\)|srand\\s*\\(' },
		message: 'Non-cryptographic random number generator — do not use for security-sensitive values',
		fix: 'Use crypto.randomBytes() (Node.js), secrets module (Python), or os.urandom() for security tokens',
		enabled: true,
		builtin: true,
		references: ['CWE-338', 'OWASP A02:2021'],
		tags: ['crypto', 'random', 'weak-rng'],
	},
	{
		id: 'SEC-008',
		domain: 'security',
		severity: 'warning',
		type: 'regex',
		pattern: 'console\\.log\\s*\\(|print\\s*\\(|printf\\s*\\(|System\\.out\\.print|logging\\.debug',
		check: { type: 'regex', pattern: 'console\\.log\\s*\\(|print\\s*\\(|printf\\s*\\(|System\\.out\\.print|logging\\.debug' },
		message: 'Debug/plain-text logging detected — ensure no sensitive data (credentials, PII, tokens) is logged',
		fix: 'Use structured logging with a log scrubber; never log passwords, tokens, or PII',
		enabled: true,
		builtin: true,
		references: ['CWE-532', 'OWASP A09:2021'],
		tags: ['logging', 'pii', 'debug'],
	},
	{
		id: 'SEC-009',
		domain: 'security',
		severity: 'error',
		type: 'regex',
		pattern: 'verify\\s*=\\s*False|ssl_verify\\s*=\\s*false|rejectUnauthorized\\s*:\\s*false|InsecureRequestWarning|urllib3\\.disable_warnings|NODE_TLS_REJECT_UNAUTHORIZED\\s*=\\s*["\']0["\']',
		check: { type: 'regex', pattern: 'verify\\s*=\\s*False|ssl_verify\\s*=\\s*false|rejectUnauthorized\\s*:\\s*false|InsecureRequestWarning|urllib3\\.disable_warnings|NODE_TLS_REJECT_UNAUTHORIZED\\s*=\\s*["\']0["\']' },
		message: 'TLS/SSL certificate verification disabled — man-in-the-middle attack risk',
		fix: 'Never disable TLS verification in production. Fix the certificate instead.',
		enabled: true,
		builtin: true,
		references: ['CWE-295', 'OWASP A02:2021'],
		tags: ['tls', 'ssl', 'certificate'],
	},
	{
		id: 'SEC-010',
		domain: 'security',
		severity: 'error',
		type: 'regex',
		pattern: 'pickle\\.loads|pickle\\.load|yaml\\.load\\s*\\([^,)]+\\)|marshal\\.loads|shelve\\.open',
		check: { type: 'regex', pattern: 'pickle\\.loads|pickle\\.load|yaml\\.load\\s*\\([^,)]+\\)|marshal\\.loads|shelve\\.open' },
		message: 'Unsafe deserialization — can lead to arbitrary code execution',
		fix: 'Use yaml.safe_load(), avoid pickle with untrusted data, use signed/schema-validated formats',
		enabled: true,
		builtin: true,
		references: ['CWE-502', 'OWASP A08:2021'],
		tags: ['deserialization', 'injection'],
	},
	{
		id: 'SEC-011',
		domain: 'security',
		severity: 'error',
		type: 'regex',
		pattern: '\\.\\./\\.\\.|path\\.join.*req\\.|__dirname.*req\\.|os\\.path\\.join.*request',
		check: { type: 'regex', pattern: '\\.\\./\\.\\.|path\\.join.*req\\.|__dirname.*req\\.|os\\.path\\.join.*request' },
		message: 'Potential path traversal — user-controlled path component may escape intended directory',
		fix: 'Normalize path and verify it starts with the intended base directory after resolution',
		enabled: true,
		builtin: true,
		references: ['CWE-22', 'OWASP A01:2021'],
		tags: ['path-traversal', 'lfi'],
	},
	{
		id: 'SEC-012',
		domain: 'security',
		severity: 'error',
		type: 'regex',
		pattern: 'DES\\.new|DESede|Cipher\\.getInstance\\s*\\(["\']DES|AES/ECB|AES_128_ECB|EVP_EncryptInit_ex.*EVP_des',
		check: { type: 'regex', pattern: 'DES\\.new|DESede|Cipher\\.getInstance\\s*\\(["\']DES|AES/ECB|AES_128_ECB|EVP_EncryptInit_ex.*EVP_des' },
		message: 'Weak or broken encryption algorithm (DES/3DES/AES-ECB) — use AES-256-GCM or ChaCha20-Poly1305',
		fix: 'Upgrade to AES-256-GCM with authenticated encryption (AEAD)',
		enabled: true,
		builtin: true,
		references: ['CWE-327', 'OWASP A02:2021'],
		tags: ['crypto', 'weak-cipher'],
	},
	{
		id: 'SEC-013',
		domain: 'security',
		severity: 'warning',
		type: 'regex',
		pattern: 'TODO.*(?:security|auth|token|secret|password|vuln|exploit|hack|bypass|FIXME)',
		check: { type: 'regex', pattern: 'TODO.*(?:security|auth|token|secret|password|vuln|exploit|hack|bypass|FIXME)' },
		message: 'Security-related TODO/FIXME found — unresolved security debt',
		fix: 'Resolve the security concern before shipping to production',
		enabled: true,
		builtin: true,
		references: [],
		tags: ['tech-debt', 'security'],
	},
	{
		id: 'SEC-014',
		domain: 'security',
		severity: 'error',
		type: 'regex',
		pattern: 'new Function\\s*\\(',
		check: { type: 'regex', pattern: 'new Function\\s*\\(' },
		message: 'Dynamic function construction via new Function() — code injection risk',
		fix: 'Avoid new Function() with dynamic arguments; use static functions or safe parsers',
		enabled: true,
		builtin: true,
		references: ['CWE-95', 'OWASP A03:2021'],
		tags: ['injection', 'code-execution'],
	},
	{
		id: 'SEC-015',
		domain: 'security',
		severity: 'error',
		type: 'regex',
		pattern: 'RSA\\.generate_private_key|rsa\\.GenerateKey|new\\s+RSA\\s*\\(\\s*(?:512|1024)\\b',
		check: { type: 'regex', pattern: 'RSA\\.generate_private_key|rsa\\.GenerateKey|new\\s+RSA\\s*\\(\\s*(?:512|1024)\\b' },
		message: 'RSA key size may be insufficient — use at minimum 2048-bit, prefer 4096-bit keys',
		fix: 'Use key_size >= 2048 (RSA) or ECDSA P-256/P-384 equivalent strength',
		enabled: true,
		builtin: true,
		references: ['CWE-326', 'NIST SP 800-57'],
		tags: ['crypto', 'key-size', 'rsa'],
	},
];


// ─── Data Integrity Rules ─────────────────────────────────────────────────────

const DATA_INTEGRITY_RULES: IGRCRule[] = [
	{
		id: 'DI-001',
		domain: 'data-integrity',
		severity: 'error',
		type: 'regex',
		pattern: 'SELECT.*FROM.*\\+|WHERE.*\\+|INSERT INTO.*\\+|UPDATE.*SET.*\\+',
		check: { type: 'regex', pattern: 'SELECT.*FROM.*\\+|WHERE.*\\+|INSERT INTO.*\\+|UPDATE.*SET.*\\+' },
		message: 'Potential SQL injection — string concatenation in SQL query',
		fix: 'Use parameterized queries or prepared statements (?, $1, :param syntax)',
		enabled: true,
		builtin: true,
		references: ['CWE-89', 'OWASP A03:2021'],
		tags: ['sql-injection', 'injection'],
	},
	{
		id: 'DI-002',
		domain: 'data-integrity',
		severity: 'error',
		type: 'regex',
		pattern: '\\.find\\s*\\(\\{.*\\$where|\\$function|\\$accumulator|\\$eval|mapReduce',
		check: { type: 'regex', pattern: '\\.find\\s*\\(\\{.*\\$where|\\$function|\\$accumulator|\\$eval|mapReduce' },
		message: 'Potential NoSQL injection — operator injection via user-controlled query fields',
		fix: 'Validate and sanitize query objects; reject inputs containing $ operators',
		enabled: true,
		builtin: true,
		references: ['CWE-943', 'OWASP A03:2021'],
		tags: ['nosql-injection', 'injection'],
	},
	{
		id: 'DI-003',
		domain: 'data-integrity',
		severity: 'warning',
		type: 'regex',
		pattern: 'DROP TABLE|DROP DATABASE|TRUNCATE TABLE|DELETE FROM [^\\n]*WITHOUT|ALTER TABLE.*DROP',
		check: { type: 'regex', pattern: 'DROP TABLE|DROP DATABASE|TRUNCATE TABLE|DELETE FROM [^\\n]*WITHOUT|ALTER TABLE.*DROP' },
		message: 'Destructive SQL operation detected — ensure this is intentional and guarded by a transaction',
		fix: 'Wrap in a transaction with explicit COMMIT; add safeguards to prevent accidental execution',
		enabled: true,
		builtin: true,
		references: ['CWE-564'],
		tags: ['sql', 'destructive'],
	},
	{
		id: 'DI-004',
		domain: 'data-integrity',
		severity: 'warning',
		type: 'regex',
		pattern: 'fs\\.writeFile|fs\\.writeFileSync|open\\s*\\(.*["\']w["\']|fopen\\s*\\(.*["\']w["\']',
		check: { type: 'regex', pattern: 'fs\\.writeFile|fs\\.writeFileSync|open\\s*\\(.*["\']w["\']|fopen\\s*\\(.*["\']w["\']' },
		message: 'File write operation — verify path is not user-controlled and destination is safe',
		fix: 'Validate and normalize file paths; ensure writing to intended directories only',
		enabled: true,
		builtin: true,
		references: ['CWE-22', 'CWE-73'],
		tags: ['file-write', 'path'],
	},
];


// ─── Privacy Rules ────────────────────────────────────────────────────────────

const PRIVACY_RULES: IGRCRule[] = [
	{
		id: 'PRIV-001',
		domain: 'privacy',
		severity: 'error',
		type: 'regex',
		pattern: '\\b(ssn|social_security|sin_number|national_id|passport_number|date_of_birth|dob|credit_card|card_number|cvv|pan_number)\\b',
		check: { type: 'regex', pattern: '\\b(ssn|social_security|sin_number|national_id|passport_number|date_of_birth|dob|credit_card|card_number|cvv|pan_number)\\b' },
		message: 'Potential PII/sensitive personal data identifier — verify GDPR/CCPA/HIPAA compliance',
		fix: 'Ensure PII is encrypted at rest and in transit; apply data minimization principles',
		enabled: true,
		builtin: true,
		references: ['GDPR Art. 9', 'CCPA 1798.140', 'HIPAA 45 CFR 164.514'],
		tags: ['pii', 'gdpr', 'hipaa', 'privacy'],
	},
	{
		id: 'PRIV-002',
		domain: 'privacy',
		severity: 'warning',
		type: 'regex',
		pattern: '\\b(email|phone|mobile|address|ip_address|geolocation|location|coordinates)\\s*[=:]',
		check: { type: 'regex', pattern: '\\b(email|phone|mobile|address|ip_address|geolocation|location|coordinates)\\s*[=:]' },
		message: 'Personal data field detected — ensure GDPR/privacy-by-design handling',
		fix: 'Apply data minimization, purpose limitation, and obtain consent per GDPR Art. 5',
		enabled: true,
		builtin: true,
		references: ['GDPR Art. 5', 'CCPA 1798.100'],
		tags: ['pii', 'gdpr', 'privacy'],
	},
];


// ─── Fail-Safe / Reliability Rules ───────────────────────────────────────────

const FAILSAFE_RULES: IGRCRule[] = [
	{
		id: 'FS-001',
		domain: 'fail-safe',
		severity: 'warning',
		type: 'regex',
		pattern: 'catch\\s*\\(.*\\)\\s*\\{\\s*\\}|except\\s*:?\\s*\\n\\s*pass\\b|rescue\\s*=>\\s*nil',
		check: { type: 'regex', pattern: 'catch\\s*\\(.*\\)\\s*\\{\\s*\\}|except\\s*:?\\s*\\n\\s*pass\\b|rescue\\s*=>\\s*nil' },
		message: 'Empty catch/except block — exception silently swallowed, hiding failures',
		fix: 'At minimum log the exception; handle or re-throw appropriately',
		enabled: true,
		builtin: true,
		references: ['CWE-390'],
		tags: ['exception', 'error-handling'],
	},
	{
		id: 'FS-002',
		domain: 'fail-safe',
		severity: 'error',
		type: 'regex',
		pattern: 'while\\s*\\(\\s*true\\s*\\)|while\\s*\\(\\s*1\\s*\\)|for\\s*\\(\\s*;\\s*;\\s*\\)',
		check: { type: 'regex', pattern: 'while\\s*\\(\\s*true\\s*\\)|while\\s*\\(\\s*1\\s*\\)|for\\s*\\(\\s*;\\s*;\\s*\\)' },
		message: 'Unconditional infinite loop without visible exit condition — potential DoS or freeze risk',
		fix: 'Add explicit break/return conditions; consider timeout/watchdog mechanisms',
		enabled: true,
		builtin: true,
		references: ['CWE-835'],
		tags: ['infinite-loop', 'dos', 'reliability'],
		// C/C++/embedded files have intentional while(1) patterns in fault-trap handlers
		// (Default_Handler, Reset_Handler) and startup code. The context-aware
		// IndustrialIotAnalyzer (IOT-001) and CStructuralAnalyzer handle those files
		// with function-name guards, so this regex rule defers to them entirely.
		skipLanguages: ['c', 'cpp', 'c_cpp', 'embedded-c', 'embedded-cpp', 'cc', 'cxx', 'h', 'hpp'],
	},
	{
		id: 'FS-003',
		domain: 'fail-safe',
		severity: 'warning',
		type: 'regex',
		pattern: 'Promise\\.all\\s*\\(|Promise\\.allSettled\\s*\\(|asyncio\\.gather\\s*\\(',
		check: { type: 'regex', pattern: 'Promise\\.all\\s*\\(|Promise\\.allSettled\\s*\\(|asyncio\\.gather\\s*\\(' },
		message: 'Concurrent async operations — verify error handling covers all individual promise rejections',
		fix: 'Use Promise.allSettled() and check each result; or wrap individual promises in try/catch',
		enabled: true,
		builtin: true,
		references: ['CWE-703'],
		tags: ['async', 'error-handling'],
	},
	{
		id: 'FS-004',
		domain: 'fail-safe',
		severity: 'warning',
		type: 'regex',
		pattern: 'process\\.exit\\s*\\(|os\\._exit\\s*\\(|System\\.exit\\s*\\(|exit\\s*\\(\\s*[1-9]',
		check: { type: 'regex', pattern: 'process\\.exit\\s*\\(|os\\._exit\\s*\\(|System\\.exit\\s*\\(|exit\\s*\\(\\s*[1-9]' },
		message: 'Hard process exit — bypasses cleanup handlers, may leave resources/locks unclosed',
		fix: 'Use graceful shutdown patterns; register cleanup handlers via atexit/SIGTERM',
		enabled: true,
		builtin: true,
		references: ['CWE-404'],
		tags: ['process-exit', 'resource-leak'],
	},
];


// ─── Architecture Rules ───────────────────────────────────────────────────────

const ARCHITECTURE_RULES: IGRCRule[] = [
	{
		id: 'ARCH-001',
		domain: 'architecture',
		severity: 'info',
		type: 'file-level',
		pattern: '',
		check: { type: 'file-level', detect: 'max-lines', threshold: 800 },
		message: 'File exceeds 800 lines — consider splitting into smaller, focused modules',
		fix: 'Extract distinct responsibilities into separate files',
		enabled: true,
		builtin: true,
		references: ['Clean Code: Single Responsibility Principle'],
		tags: ['size', 'complexity'],
	},
	{
		id: 'ARCH-002',
		domain: 'architecture',
		severity: 'warning',
		type: 'regex',
		pattern: 'debugger\\b',
		check: { type: 'regex', pattern: 'debugger\\b' },
		message: 'Debugger statement left in code — must be removed before production',
		fix: 'Remove all debugger statements before committing',
		enabled: true,
		builtin: true,
		references: [],
		tags: ['debug', 'production'],
	},
	{
		id: 'ARCH-003',
		domain: 'architecture',
		severity: 'warning',
		type: 'regex',
		pattern: '0\\.0\\.0\\.0|127\\.0\\.0\\.1|localhost',
		check: { type: 'regex', pattern: '0\\.0\\.0\\.0|127\\.0\\.0\\.1|localhost' },
		message: 'Hardcoded network address detected — use configuration for host/address binding',
		fix: 'Use environment variables or configuration files for network addresses',
		enabled: true,
		builtin: true,
		references: ['CWE-1198'],
		tags: ['hardcoded', 'network', 'config'],
	},
];


// ─── C/C++ Structural Rules (MISRA C, AUTOSAR, ISO 26262) ────────────────────

const C_STRUCTURAL_RULES: IGRCRule[] = [
	{
		id: 'MISRA-001',
		domain: 'automotive',
		severity: 'error',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'goto-usage' },
		message: 'MISRA C Rule 15.1 — goto statement is not permitted in safety-critical C code',
		fix: 'Replace goto with structured control flow (loops, break, return)',
		enabled: true,
		builtin: true,
		references: ['MISRA C 2012 Rule 15.1', 'ISO 26262-6'],
		tags: ['misra', 'goto', 'automotive'],
	},
	{
		id: 'MISRA-002',
		domain: 'automotive',
		severity: 'error',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'recursive-call' },
		message: 'MISRA C Rule 17.2 — recursive functions not permitted (unbounded stack growth)',
		fix: 'Refactor into iterative form with explicit stack/state management',
		enabled: true,
		builtin: true,
		references: ['MISRA C 2012 Rule 17.2', 'ISO 26262-6 Table 5'],
		tags: ['misra', 'recursion', 'automotive', 'stack'],
	},
	{
		id: 'MISRA-003',
		domain: 'automotive',
		severity: 'error',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'dynamic-memory' },
		message: 'MISRA C Rule 21.3 — dynamic memory allocation (malloc/free) not permitted after initialization',
		fix: 'Pre-allocate all memory statically at startup; use memory pools instead of malloc/free',
		enabled: true,
		builtin: true,
		references: ['MISRA C 2012 Rule 21.3', 'DO-178C', 'ISO 26262-6'],
		tags: ['misra', 'dynamic-memory', 'automotive'],
	},
	{
		id: 'MISRA-004',
		domain: 'automotive',
		severity: 'error',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'unbounded-recursion' },
		message: 'ISO 26262 — recursion without depth guard; stack overflow risk',
		fix: 'Add recursion depth counter and abort when limit exceeded; or convert to iteration',
		enabled: true,
		builtin: true,
		references: ['ISO 26262-6 Table 5', 'IEC 61508-3 B.7'],
		tags: ['recursion', 'stack-overflow', 'iso26262'],
	},
	{
		id: 'MISRA-005',
		domain: 'firmware',
		severity: 'error',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'isr-shared-state' },
		message: 'ISR accesses global variable without volatile qualifier or critical section',
		fix: 'Declare shared variables as volatile and protect with critical section or atomic access',
		enabled: true,
		builtin: true,
		references: ['MISRA C 2012 Rule 19.1', 'IEC 61508-3'],
		tags: ['isr', 'interrupt', 'volatile', 'firmware'],
	},
	{
		id: 'MISRA-006',
		domain: 'firmware',
		severity: 'error',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'isr-blocking-call' },
		message: 'ISR contains blocking call — ISRs must be non-blocking to avoid system lockup',
		fix: 'Remove blocking calls from ISRs; use flags/queues to defer work to task context',
		enabled: true,
		builtin: true,
		references: ['MISRA C 2012 Dir 1.1', 'RTOS safety guidelines'],
		tags: ['isr', 'interrupt', 'blocking', 'firmware'],
	},
	{
		id: 'MISRA-007',
		domain: 'automotive',
		severity: 'warning',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'misra-implicit-type' },
		message: 'MISRA C Rule 8.1 — implicit function declarations not permitted',
		fix: 'Add explicit function prototype declarations in header files',
		enabled: true,
		builtin: true,
		references: ['MISRA C 2012 Rule 8.1'],
		tags: ['misra', 'implicit-type', 'automotive'],
	},
	{
		id: 'MISRA-008',
		domain: 'automotive',
		severity: 'warning',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'misra-no-else' },
		message: 'MISRA C Rule 15.7 — if-else chain without final else branch',
		fix: 'Add explicit else clause (even if empty with a MISRA deviation comment)',
		enabled: true,
		builtin: true,
		references: ['MISRA C 2012 Rule 15.7'],
		tags: ['misra', 'else', 'automotive'],
	},
	{
		id: 'MISRA-009',
		domain: 'automotive',
		severity: 'warning',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'misra-switch-default' },
		message: 'MISRA C Rule 16.4 — switch statement without default clause',
		fix: 'Add default: clause handling unexpected values (assert or safe default action)',
		enabled: true,
		builtin: true,
		references: ['MISRA C 2012 Rule 16.4'],
		tags: ['misra', 'switch', 'automotive'],
	},
	{
		id: 'MISRA-010',
		domain: 'automotive',
		severity: 'warning',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'misra-multiple-return' },
		message: 'MISRA C Rule 15.5 — function has multiple return statements',
		fix: 'Refactor to single-exit function using a result variable and single return',
		enabled: true,
		builtin: true,
		references: ['MISRA C 2012 Rule 15.5'],
		tags: ['misra', 'multiple-return', 'automotive'],
	},
	{
		id: 'MISRA-011',
		domain: 'automotive',
		severity: 'error',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'autosar-layer-violation' },
		message: 'AUTOSAR: illegal cross-layer include detected (e.g. Application \u2192 MCAL direct)',
		fix: 'Route all cross-layer communication through the defined AUTOSAR API (RTE, COM, PDU Router)',
		enabled: true,
		builtin: true,
		references: ['AUTOSAR SWS_BSW_General', 'ISO 26262-6'],
		tags: ['autosar', 'layer', 'automotive'],
	},
	{
		id: 'MISRA-012',
		domain: 'automotive',
		severity: 'warning',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'unsafe-pointer-cast' },
		message: 'Pointer cast without MISRA deviation justification comment',
		fix: 'Add /* MISRA justified: <reason> */ comment; use type-safe abstractions where possible',
		enabled: true,
		builtin: true,
		references: ['MISRA C 2012 Rule 11.1', 'MISRA C 2012 Rule 11.3'],
		tags: ['misra', 'pointer-cast', 'automotive'],
	},
	{
		id: 'MISRA-013',
		domain: 'firmware',
		severity: 'error',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'stack-overflow-risk' },
		message: 'Large local array or VLA on stack — potential stack overflow in embedded system',
		fix: 'Move large buffers to static/global scope or use heap allocation with bounds checking',
		enabled: true,
		builtin: true,
		references: ['IEC 61508-3 B.7', 'MISRA C 2012 Dir 4.13'],
		tags: ['stack', 'overflow', 'embedded', 'firmware'],
	},
	{
		id: 'MISRA-014',
		domain: 'firmware',
		severity: 'error',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'missing-volatile-shared' },
		message: 'Variable shared between ISR and task context lacks volatile qualifier',
		fix: 'Declare as volatile; use atomic_t or critical section for read-modify-write operations',
		enabled: true,
		builtin: true,
		references: ['MISRA C 2012 Rule 19.1', 'IEC 61508-3'],
		tags: ['volatile', 'isr', 'shared-state', 'firmware'],
	},
	{
		id: 'MISRA-015',
		domain: 'automotive',
		severity: 'error',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'missing-error-propagation' },
		message: 'Safety function return value not checked — error silently ignored',
		fix: 'Always check return values of safety-critical functions and propagate or handle errors',
		enabled: true,
		builtin: true,
		references: ['MISRA C 2012 Dir 4.7', 'ISO 26262-6'],
		tags: ['misra', 'error-propagation', 'automotive'],
	},

	{
		id: 'FIRM-001',
		domain: 'firmware',
		severity: 'error',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'polling-without-timeout' },
		message: 'Hardware polling loop with no timeout — CPU blocks forever if peripheral is unresponsive or its clock not enabled',
		fix: 'Add a timeout counter: uint32_t t = TIMEOUT_VALUE; while (!(REG & FLAG) && t-- > 0U) {} if (t == 0U) { /* handle error */ }',
		enabled: true,
		builtin: true,
		references: ['IEC 61508-2 §7.4.3', 'MISRA C 2012 Dir 4.1', 'ISO 26262-6 §8.4.5'],
		tags: ['polling', 'timeout', 'livelock', 'firmware', 'embedded'],
	},
	{
		id: 'FIRM-002',
		domain: 'firmware',
		severity: 'error',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'timeout-without-recovery' },
		message: 'Timeout loop has no recovery check after exit — if the waited condition never occurred, execution continues in a degraded state',
		fix: 'After the timeout loop: if (timeout == 0U) { /* NVIC_SystemReset(), set error flag, or halt */ }',
		enabled: true,
		builtin: true,
		references: ['IEC 61508-2 §7.4.3', 'ISO 26262-6 §8.4.5'],
		tags: ['timeout', 'clock', 'pll', 'firmware', 'embedded'],
	},
	{
		id: 'FIRM-003',
		domain: 'firmware',
		severity: 'warning',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'non-atomic-output-register' },
		message: 'Output register modified via read-modify-write — not atomic; an ISR writing the same register concurrently will corrupt this write',
		fix: 'Use the atomic set/reset register (BSRR/BSRL on STM32, PORT SET/CLR on AVR/SAM) instead of reading and writing back ODR/PORT directly',
		enabled: true,
		builtin: true,
		references: ['ARM Cortex-M Application Note AN321', 'MISRA C 2012 Rule 12.1', 'IEC 61508-3 B.9'],
		tags: ['gpio', 'atomic', 'isr', 'race-condition', 'firmware', 'embedded'],
	},
	{
		id: 'FIRM-004',
		domain: 'firmware',
		severity: 'warning',
		type: 'c-structural',
		pattern: '',
		check: { type: 'c-structural', detect: 'unbounded-string-loop' },
		message: 'String traversal loop with no maximum length guard — reads unbounded memory if string is not null-terminated',
		fix: 'Add a length parameter and bound the loop: while (*p != \'\\0\' && len-- > 0U) — or use strnlen()/strlcpy()',
		enabled: true,
		builtin: true,
		references: ['CWE-125', 'CWE-126', 'MISRA C 2012 Rule 17.7'],
		tags: ['string', 'bounds', 'buffer', 'firmware', 'embedded'],
	},
];


// ─── ICS / SCADA Security Rules (IEC 62443, NERC CIP) ────────────────────────

const ICS_SECURITY_RULES: IGRCRule[] = [
	{
		id: 'ICS-001',
		domain: 'ics-security',
		severity: 'error',
		type: 'ics-security',
		pattern: '',
		check: { type: 'ics-security', detect: 'hardcoded-credential' },
		message: 'Hardcoded credential in ICS/SCADA code — IEC 62443-3-3 SR 1.5 violation',
		fix: 'Store credentials in an industrial secrets manager or HSM; rotate regularly',
		enabled: true,
		builtin: true,
		references: ['IEC 62443-3-3 SR 1.5', 'NERC CIP-007-6 R5'],
		tags: ['ics', 'scada', 'credential', 'iec62443'],
	},
	{
		id: 'ICS-002',
		domain: 'ics-security',
		severity: 'error',
		type: 'ics-security',
		pattern: '',
		check: { type: 'ics-security', detect: 'scada-unauthenticated' },
		message: 'SCADA protocol communication without authentication — IEC 62443-3-3 SR 1.2 violation',
		fix: 'Implement authentication for all SCADA protocol sessions per IEC 62443-3-3 SR 1.2',
		enabled: true,
		builtin: true,
		references: ['IEC 62443-3-3 SR 1.2', 'NERC CIP-005-6'],
		tags: ['ics', 'scada', 'authentication', 'iec62443'],
	},
	{
		id: 'ICS-003',
		domain: 'ics-security',
		severity: 'error',
		type: 'ics-security',
		pattern: '',
		check: { type: 'ics-security', detect: 'dnp3-no-auth' },
		message: 'DNP3 session without Secure Authentication v5 (SAv5) — IEC 62351-5 violation',
		fix: 'Configure SAv5 challenge-response authentication for all DNP3 sessions',
		enabled: true,
		builtin: true,
		references: ['IEC 62351-5', 'IEEE 1815', 'NERC CIP-007'],
		tags: ['dnp3', 'ics', 'authentication'],
	},
	{
		id: 'ICS-004',
		domain: 'ics-security',
		severity: 'error',
		type: 'ics-security',
		pattern: '',
		check: { type: 'ics-security', detect: 'modbus-no-whitelist' },
		message: 'Modbus TCP server without IP whitelist — unauthorized access risk (IEC 62443-3-3 SR 5.2)',
		fix: 'Implement source IP allowlisting for all Modbus TCP server endpoints',
		enabled: true,
		builtin: true,
		references: ['IEC 62443-3-3 SR 5.2', 'NERC CIP-005-6'],
		tags: ['modbus', 'ics', 'whitelist'],
	},
	{
		id: 'ICS-005',
		domain: 'ics-security',
		severity: 'error',
		type: 'ics-security',
		pattern: '',
		check: { type: 'ics-security', detect: 'opc-ua-no-security' },
		message: 'OPC-UA endpoint with SecurityMode.None — unauthenticated access permitted',
		fix: 'Set SecurityMode to Sign or SignAndEncrypt; configure x509 certificates per IEC 62541',
		enabled: true,
		builtin: true,
		references: ['IEC 62541', 'IEC 62443-3-3 SR 4.1'],
		tags: ['opc-ua', 'ics', 'tls', 'authentication'],
	},
	{
		id: 'ICS-006',
		domain: 'ics-security',
		severity: 'error',
		type: 'ics-security',
		pattern: '',
		check: { type: 'ics-security', detect: 'iec61850-unprotected' },
		message: 'IEC 61850 GOOSE/MMS without IEC 62351 authentication — protection relay spoofing risk',
		fix: 'Implement IEC 62351-6 GOOSE authentication and IEC 62351-4 MMS TLS',
		enabled: true,
		builtin: true,
		references: ['IEC 62351-6', 'IEC 62351-4', 'IEC 61850'],
		tags: ['iec61850', 'goose', 'mms', 'protection-relay'],
	},
	{
		id: 'ICS-007',
		domain: 'ics-security',
		severity: 'warning',
		type: 'ics-security',
		pattern: '',
		check: { type: 'ics-security', detect: 'engineering-station-path' },
		message: 'Hardcoded path to engineering station or SCADA server',
		fix: 'Use configurable endpoints; avoid hardcoding network paths to field devices',
		enabled: true,
		builtin: true,
		references: ['IEC 62443-3-3', 'NERC CIP-005'],
		tags: ['ics', 'scada', 'hardcoded-path'],
	},
	{
		id: 'ICS-008',
		domain: 'ics-security',
		severity: 'error',
		type: 'ics-security',
		pattern: '',
		check: { type: 'ics-security', detect: 'cleartext-ot-protocol' },
		message: 'OT protocol data logged or transmitted in cleartext — NERC CIP-007 / IEC 62443-3-3 SR 3.1 violation',
		fix: 'Encrypt OT communications; use confidential logging patterns for process values',
		enabled: true,
		builtin: true,
		references: ['IEC 62443-3-3 SR 3.1', 'NERC CIP-007-6 R4'],
		tags: ['ics', 'cleartext', 'logging'],
	},
	{
		id: 'ICS-009',
		domain: 'ics-security',
		severity: 'error',
		type: 'ics-security',
		pattern: '',
		check: { type: 'ics-security', detect: 'missing-network-isolation' },
		message: 'OT/IT zone crossing without DMZ or firewall reference — IEC 62443-3-2 zone/conduit violation',
		fix: 'Route OT-to-IT traffic through a security gateway or DMZ per IEC 62443-3-2',
		enabled: true,
		builtin: true,
		references: ['IEC 62443-3-2', 'NERC CIP-005-6'],
		tags: ['ics', 'network-isolation', 'dmz'],
	},
	{
		id: 'ICS-010',
		domain: 'ics-security',
		severity: 'error',
		type: 'ics-security',
		pattern: '',
		check: { type: 'ics-security', detect: 'unsafe-firmware-update' },
		message: 'Firmware update without signature/hash verification — IEC 62443-4-2 CR 3.4 violation',
		fix: 'Verify firmware signature or hash before flashing; use secure boot',
		enabled: true,
		builtin: true,
		references: ['IEC 62443-4-2 CR 3.4', 'NIST SP 800-193'],
		tags: ['firmware', 'update', 'signature', 'ics'],
	},
];


// ─── Telecom & 5G Security Rules (3GPP, GSMA, SIP, GTP, Diameter) ───────────

const TELECOM_SECURITY_RULES: IGRCRule[] = [
	{
		id: 'TC-001',
		domain: 'telecom-security',
		severity: 'error',
		type: 'telecom-security',
		pattern: '',
		check: { type: 'telecom-security', detect: 'imsi-plaintext-log' },
		message: 'IMSI/SUPI/MSISDN logged or transmitted in plaintext — 3GPP TS 33.501 subscriber privacy violation',
		fix: 'Use SUCI concealment for SUPI; pseudonymize subscriber identifiers in logs',
		enabled: true,
		builtin: true,
		references: ['3GPP TS 33.501', 'GSMA FS.40', 'ETSI TS 133 501'],
		tags: ['telecom', '5g', 'imsi', 'privacy'],
	},
	{
		id: 'TC-002',
		domain: 'telecom-security',
		severity: 'error',
		type: 'telecom-security',
		pattern: '',
		check: { type: 'telecom-security', detect: 'sip-header-injection' },
		message: 'Unsanitized user input in SIP header construction — SIP header injection risk',
		fix: 'Sanitize all inputs before inserting into SIP headers; validate against RFC 3261 grammar',
		enabled: true,
		builtin: true,
		references: ['RFC 3261', 'OWASP A03:2021', 'GSMA FS.11'],
		tags: ['sip', 'injection', 'telecom'],
	},
	{
		id: 'TC-003',
		domain: 'telecom-security',
		severity: 'error',
		type: 'telecom-security',
		pattern: '',
		check: { type: 'telecom-security', detect: 'gtp-missing-validation' },
		message: 'GTP tunnel created without TEID/source address validation — GTP-U/C hijacking risk',
		fix: 'Validate TEID and source IP; implement GTP firewall rules per 3GPP TS 33.117',
		enabled: true,
		builtin: true,
		references: ['3GPP TS 33.117', '3GPP TS 29.274', 'GSMA FS.19'],
		tags: ['gtp', 'tunnel', 'validation', 'telecom'],
	},
	{
		id: 'TC-004',
		domain: 'telecom-security',
		severity: 'error',
		type: 'telecom-security',
		pattern: '',
		check: { type: 'telecom-security', detect: 'nas-unprotected' },
		message: 'NAS message sent without integrity protection or confidentiality — 3GPP TS 33.501 violation',
		fix: 'Apply NAS security algorithms (5G-EA/5G-IA or 4G equivalents) for all NAS messages',
		enabled: true,
		builtin: true,
		references: ['3GPP TS 33.501', '3GPP TS 33.401'],
		tags: ['nas', '5g', '4g', 'integrity', 'telecom'],
	},
	{
		id: 'TC-005',
		domain: 'telecom-security',
		severity: 'error',
		type: 'telecom-security',
		pattern: '',
		check: { type: 'telecom-security', detect: 'diameter-no-tls' },
		message: 'Diameter interface (Ro/Rf/S6a) without TLS or IPsec — 3GPP TS 33.210 violation',
		fix: 'Configure DTLS/TLS for all Diameter connections per 3GPP TS 33.210',
		enabled: true,
		builtin: true,
		references: ['3GPP TS 33.210', 'RFC 6733', 'RFC 5866'],
		tags: ['diameter', 'tls', 'telecom'],
	},
	{
		id: 'TC-006',
		domain: 'telecom-security',
		severity: 'error',
		type: 'telecom-security',
		pattern: '',
		check: { type: 'telecom-security', detect: 'ss7-unfiltered' },
		message: 'SS7 MAP/ISUP processing without firewall checks — location tracking and call interception risk',
		fix: 'Implement SS7 firewall rules per GSMA FS.11; filter Category 1/2/3 threats',
		enabled: true,
		builtin: true,
		references: ['GSMA FS.11', 'GSMA FS.07', '3GPP TS 29.002'],
		tags: ['ss7', 'map', 'telecom', 'legacy'],
	},
	{
		id: 'TC-007',
		domain: 'telecom-security',
		severity: 'error',
		type: 'telecom-security',
		pattern: '',
		check: { type: 'telecom-security', detect: 'suci-concealment-skip' },
		message: 'SUPI transmitted without SUCI concealment (5G NR) — subscriber tracking vulnerability',
		fix: 'Implement SUCI concealment using ECIES-Profile-A or Profile-B per 3GPP TS 33.501',
		enabled: true,
		builtin: true,
		references: ['3GPP TS 33.501 Section 6.12', 'GSMA FS.40'],
		tags: ['5g', 'suci', 'supi', 'privacy', 'telecom'],
	},
	{
		id: 'TC-008',
		domain: 'telecom-security',
		severity: 'error',
		type: 'telecom-security',
		pattern: '',
		check: { type: 'telecom-security', detect: 'ki-plaintext' },
		message: 'Authentication key (Ki/K/AUTN) in plaintext — HSS/UDM key material must be protected',
		fix: 'Store Ki/K in HSM; never log, print, or store authentication keys in plaintext',
		enabled: true,
		builtin: true,
		references: ['3GPP TS 33.102', '3GPP TS 33.501', 'GSMA FS.16'],
		tags: ['ki', 'auth-key', 'hsm', 'telecom'],
	},
	{
		id: 'TC-009',
		domain: 'telecom-security',
		severity: 'error',
		type: 'telecom-security',
		pattern: '',
		check: { type: 'telecom-security', detect: 'lawful-intercept-gap' },
		message: 'Lawful Intercept (LI) trigger path disabled or bypassed — ETSI ES 201 671 / CALEA compliance gap',
		fix: 'Ensure LI interface is always active; never bypass LI triggers in production code',
		enabled: true,
		builtin: true,
		references: ['ETSI ES 201 671', 'CALEA', '3GPP TS 33.107', '3GPP TS 33.108'],
		tags: ['lawful-intercept', 'li', 'compliance', 'telecom'],
	},
];


// ─── Industrial IoT / OT Safety Rules ────────────────────────────────────────

const IOT_OT_RULES: IGRCRule[] = [
	{
		id: 'IOT-001',
		domain: 'ot-safety',
		severity: 'error',
		type: 'iot-ot',
		pattern: '',
		check: { type: 'iot-ot', detect: 'missing-watchdog' },
		message: 'Infinite loop or real-time task without watchdog kick — system lockup risk (IEC 61508 B.5)',
		fix: 'Add watchdog_kick()/WDT_Feed() call at the bottom of every infinite loop in RT tasks',
		enabled: true,
		builtin: true,
		references: ['IEC 61508-3 B.5', 'IEC 62443-4-2', 'ISA-99'],
		tags: ['watchdog', 'rtos', 'iot', 'ot', 'safety'],
	},
	{
		id: 'IOT-002',
		domain: 'ot-safety',
		severity: 'error',
		type: 'iot-ot',
		pattern: '',
		check: { type: 'iot-ot', detect: 'heap-in-rt-task' },
		message: 'Dynamic memory allocation in real-time task or ISR — non-deterministic execution time',
		fix: 'Pre-allocate buffers statically or use fixed-size memory pools; avoid malloc/free in RT context',
		enabled: true,
		builtin: true,
		references: ['IEC 61508-3 B.7', 'MISRA C 2012 Rule 21.3', 'DO-178C'],
		tags: ['heap', 'rtos', 'rt-task', 'determinism', 'iot'],
	},
	{
		id: 'IOT-003',
		domain: 'ot-safety',
		severity: 'error',
		type: 'iot-ot',
		pattern: '',
		check: { type: 'iot-ot', detect: 'missing-redundancy' },
		message: 'Safety-critical actuator output without redundancy voting — SIL requirement gap',
		fix: 'Implement 2oo3 or 1oo2 voting for safety outputs; add independent channel verification',
		enabled: true,
		builtin: true,
		references: ['IEC 61508-2 7.4.7', 'IEC 61511'],
		tags: ['redundancy', 'sil', 'actuator', 'safety'],
	},
	{
		id: 'IOT-004',
		domain: 'ot-safety',
		severity: 'error',
		type: 'iot-ot',
		pattern: '',
		check: { type: 'iot-ot', detect: 'determinism-violation' },
		message: 'Non-deterministic call inside real-time task — timing violations risk',
		fix: 'Remove floating-point without FPU, dynamic memory, I/O waits from RT task bodies',
		enabled: true,
		builtin: true,
		references: ['IEC 61508-3 B.7', 'DO-178C Section 6.4'],
		tags: ['determinism', 'rt-task', 'timing', 'iot'],
	},
	{
		id: 'IOT-005',
		domain: 'ot-safety',
		severity: 'error',
		type: 'iot-ot',
		pattern: '',
		check: { type: 'iot-ot', detect: 'missing-safety-check' },
		message: 'Safety function return value not checked — undetected fault propagation',
		fix: 'Always check return values of safety functions and handle E_NOT_OK / error states',
		enabled: true,
		builtin: true,
		references: ['IEC 61508-3', 'AUTOSAR SWS_BswGeneral'],
		tags: ['safety-check', 'error-propagation', 'iot'],
	},
	{
		id: 'IOT-006',
		domain: 'ot-safety',
		severity: 'error',
		type: 'iot-ot',
		pattern: '',
		check: { type: 'iot-ot', detect: 'plc-write-unprotected' },
		message: 'PLC output write without preceding interlock validation — unsafe command execution risk',
		fix: 'Validate all interlock conditions before writing PLC outputs; implement safety rated interlocking',
		enabled: true,
		builtin: true,
		references: ['IEC 61131-3', 'IEC 62443-3-3 SR 3.9', 'ISA-99'],
		tags: ['plc', 'interlock', 'ot', 'safety'],
	},
	{
		id: 'IOT-007',
		domain: 'ot-safety',
		severity: 'warning',
		type: 'iot-ot',
		pattern: '',
		check: { type: 'iot-ot', detect: 'scada-historian-direct' },
		message: 'Direct SCADA historian write without range/bounds check — data integrity violation',
		fix: 'Validate process values against engineering range before writing to historian',
		enabled: true,
		builtin: true,
		references: ['IEC 62443-3-3 SR 3.1', 'NERC CIP-007'],
		tags: ['scada', 'historian', 'bounds-check', 'ot'],
	},
	{
		id: 'IOT-008',
		domain: 'ot-safety',
		severity: 'error',
		type: 'iot-ot',
		pattern: '',
		check: { type: 'iot-ot', detect: 'ot-hardcoded-ip' },
		message: 'Hardcoded IP or MAC address for OT device communication — configuration inflexibility and security risk',
		fix: 'Use configuration files or device discovery protocols; avoid hardcoded addresses',
		enabled: true,
		builtin: true,
		references: ['IEC 62443-4-2', 'NIST SP 800-82'],
		tags: ['hardcoded-ip', 'ot', 'config'],
	},
	{
		id: 'IOT-009',
		domain: 'ot-safety',
		severity: 'error',
		type: 'iot-ot',
		pattern: '',
		check: { type: 'iot-ot', detect: 'missing-failsafe' },
		message: 'Control loop or state machine without fail-safe/fault state — SIL gap',
		fix: 'Define and implement safe state; transition to fail-safe on any unhandled error',
		enabled: true,
		builtin: true,
		references: ['IEC 61508-2 7.4.3', 'IEC 61511 9.4', 'IEC 62443-3-3'],
		tags: ['failsafe', 'state-machine', 'sil', 'ot'],
	},
	{
		id: 'IOT-010',
		domain: 'ot-safety',
		severity: 'warning',
		type: 'iot-ot',
		pattern: '',
		check: { type: 'iot-ot', detect: 'heartbeat-missing' },
		message: 'Redundant system component without heartbeat — failed node may not be detected',
		fix: 'Add periodic heartbeat signal; implement timeout-based failure detection',
		enabled: true,
		builtin: true,
		references: ['IEC 61508-2', 'IEC 62439-3'],
		tags: ['heartbeat', 'redundancy', 'iot', 'reliability'],
	},
];


// ─── All Built-in Rules ───────────────────────────────────────────────────────

export const BUILTIN_RULES: IGRCRule[] = [
	...SECURITY_RULES,
	...DATA_INTEGRITY_RULES,
	...PRIVACY_RULES,
	...FAILSAFE_RULES,
	...ARCHITECTURE_RULES,
	...C_STRUCTURAL_RULES,
	...ICS_SECURITY_RULES,
	...TELECOM_SECURITY_RULES,
	...IOT_OT_RULES,
];
